#!/usr/bin/env bash
# configure nginx to redirect

sudo touch /redirect_me
sudo touch /home/ubuntu/index.html

echo '

http {
	server {
        listen 80;
        server_name franksolutions.tech www.franksolutions.tech;

        location /redirect_me {
        return 301 /home/ubuntu/index.html;
}
}


}

' > /etc/nginx/nginx.conf
