#!/usr/bin/env bash
# creating a server clone
sudo apt update
sudo apt -y install nginx
echo 'Hello World!' > /var/www/html/*.html
franksolutions.tech

sudo touch /redirect_me
sudo touch /home/ubuntu/index.html

echo '

http {
	server {
        listen 80;
        server_name franksolutions.tech www.franksolutions.tech;

        location /redirect_me {
        return 301 /home/ubuntu/index.html;
}
}


}

' > /etc/nginx/nginx.conf
sudo touch /var/www/html/error_404.html 
echo '
http{
server{
error_page 404 /error_404.html;
root /var/www/html;
location = /error_404.html{
	internal;
	try_files $uri;	
}
}
}
"
