#!/usr/bin/env bash
# configure  haproxy load balancer

sudo apt get update
sudo apt -y install haproxy

sudo echo "
frontend front_http
	bind *:80
	stats uri /haproxy?stats
	default_backend back_http

backend back_http
	balance roundrobin
	server 91593-web-01 54.221.181.151:80 check
	server 91593-web-02 100.26.169.188:80 check

" >> /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo systemctl reload haproxy
